version: "3"
services:
  app:
    cpus: 4
    mem_limit: 8g
    build:
      context: ..
      dockerfile: ./.devcontainer/Dockerfile
    # image: datajoint/element_optogenetics:latest
    extra_hosts:
      - fakeservices.datajoint.io:127.0.0.1
    devices:
      - /dev/fuse
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    volumes:
      - ..:/workspaces/element-optogenetics:cached
      - docker_data:/var/lib/docker # persist docker images
    privileged: true # only because of dind
volumes:
  docker_data:
